config/routes.rb
Rails.application.routes.draw do
  devise_for :users,only: [:registration, :sign_in, :sign_out, :session], :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :only => [:show] do
    member do
      get :likes
    end
  end
      
root to: 'toppages#index'
  
  resources :posts, :only =>[:new,:create,:show] do
    get :search,  on: :collection
  end
  
resources :favorites, only: [:create, :destroy]

get 'gachas' => 'gachas#index'
get 'gachas/ikkai/' => 'gachas#ikkai'
get 'gachas/jukkai/' => 'gachas#jukkai'

end

app/controllers/gachas_controller.rb
class GachasController < ApplicationController
  def index
  end

  def ikkai
    @post = Post.rand.first
  end

  def jukkai
    @posts = Post.rand.first(10)
  end


end

app/views/gachas/ikkai.html.erb
<h1 class="mb-3">あるあるガチャ</h1>
<%= link_to '一回まわす', gachas_ikkai_path, class:'btn btn-lg btn-success mr-4' %><%= link_to '１０連ガチャ', gachas_jukkai_path, class:'btn btn-lg btn-primary' %>
<%= render 'posts/post_show', post: @post %>

app/views/gachas/index.html.erb
<h1 class="mb-3">あるあるガチャ</h1>
<%= link_to '一回まわす', gachas_ikkai_path, class:'btn btn-lg btn-success mr-4' %><%= link_to '１０連ガチャ', gachas_jukkai_path, class:'btn btn-lg btn-primary' %>

app/views/gachas/jukkai.html.erb
<h1 class="mb-3">あるあるガチャ</h1>
<%= link_to '一回まわす', gachas_ikkai_path, class:'btn btn-lg btn-success mr-4' %><%= link_to '１０連ガチャ', gachas_jukkai_path, class:'btn btn-lg btn-primary' %>
<%= render 'posts/posts_jukkai', posts: @posts %>