config/routes.rb
Rails.application.routes.draw do
  devise_for :users,only: [:registration, :sign_in, :sign_out, :session], :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :only => [:show] do
    member do
      get :likes
    end
  end
      
root to: 'toppages#index'
  
  resources :posts, :only =>[:new,:create,:show] do
    get :search,  on: :collection
  end
  
resources :favorites, only: [:create, :destroy]

get 'gachas' => 'gachas#index'
get 'gachas/ikkai/' => 'gachas#ikkai'
get 'gachas/jukkai/' => 'gachas#jukkai'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  
  validates :title, presence: true, length: { maximum: 30 }
  validates :content,presence: true, length: { maximum: 255 }
  
  has_many :favorites
  has_many :liked_user, through: :favorites, source: :user
  
  scope :post_sort, -> (sort)do
    if sort == 'new'
      return order('id desc')
    elsif sort == 'old'
      return order('id asc')
    elsif sort == 'popular'
      return select('posts.*', 'count(favorites.id) AS favcount').left_joins(:favorites).group('posts.id').order('favcount desc')
    elsif sort == 'unpopular'
      return select('posts.*', 'count(favorites.id) AS favcount').left_joins(:favorites).group('posts.id').order('favcount asc')
    end
  end
  
  scope :top_popular, -> { select('posts.*', 'count(favorites.id) AS favcount').left_joins(:favorites).group('posts.id').order('favcount desc').limit(10) }
  
  scope :rand, -> do
   if Rails.env.production? 
     return order('RANDOM()')
   else
     return order('rand()')
   end
  end
   
 
  


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  
  def new
    if user_signed_in?
      @post = current_user.posts.build
    else
      redirect_to new_user_session_path
    end
    
    @categories = Category.all
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'あるあるを投稿しました。'
      redirect_to @post
    else
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render 'posts/new'
    end
    
  end

  def show
    @post = Post.find(params[:id])
  end

  def search
    if search_params[:text] && search_params[:category_id].present?
     @posts = Post.where(category_id: search_params[:category_id]).where(['title LIKE ? OR content LIKE ?', "%#{search_params[:text]}%", "%#{search_params[:text]}%"]).post_sort(params[:sort]).page(params[:page]).per(25)
    elsif search_params[:category_id].present?
     @posts = Post.where(category_id: search_params[:category_id]).post_sort(params[:sort]).page(params[:page]).per(25)
    elsif search_params[:text].present?
     @posts = Post.where(['title LIKE ? OR content LIKE ?', "%#{search_params[:text]}%", "%#{search_params[:text]}%"]).post_sort(params[:sort]).page(params[:page]).per(25)
    else
     @posts = Post.all.post_sort(params[:sort]).page(params[:page]).per(25)
    end
    
      
  end
  
  
  private
    
  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end
  
  def search_params
    params.fetch(:search,{}).permit(:text,:sort, :category_id)
  end
  
end

app/views/posts/_post_show.html.erb
<div class="card mt-3">
  <div class="media-header bg-cream">
    <h5 class="ml-3 mt-1"><strong><%= link_to post.title+'あるある', post_path(post), class: 'text-dark' %></strong></h5>
  </div>  
  <div class="card-body">
   <p> <%= post.content %></p>
  </div>
  <div class="card-footer bg-white small">
    <div id="like_button-<%= post.id %>">
      <%= render 'favorites/like_button', post: post %>
    </div>
    　カテゴリー：<%= link_to post.category.type, '/posts/search?utf8=✓&search%5Bcategory_id%5D=' +  post.category.id.to_s + '&sort=id+desc&search%5Btext%5D=&commit=検索'%>
    　投稿者：<%= link_to post.user.name, user_path(post.user)%>
    <div class="mt-1" style="float: right; display: inline-block">
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="「<%= post.title %>あるある」　<%= post.content %>" data-url="https://jepapt2-aruaru.herokuapp.com/posts/<%= post.id %>" data-hashtags="あるあるnet" data-lang="ja" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
<div class="card mt-3">
  <div class="media-header bg-cream">
    <h5 class="ml-3 mt-1"><strong><%= link_to post.title+'あるある', post_path(post), class: 'text-dark' %></strong></h5>
  </div>  
  <div class="card-body">
   <p> <%= post.content %></p>
  </div>
  <div class="card-footer bg-white small">
    <div id="like_button-<%= post.id %>">
      <%= render 'favorites/like_button', post: post %>
    </div>
    　カテゴリー：<%= link_to post.category.type, '/posts/search?utf8=✓&search%5Bcategory_id%5D=' +  post.category.id.to_s + '&sort=new&search%5Btext%5D=&commit=検索'%>
    　投稿者：<%= link_to post.user.name, user_path(post.user)%>
    <div class="mt-1" style="float: right; display: inline-block">
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="「<%= post.title %>あるある」　<%= post.content %>" data-url="https://jepapt2-aruaru.herokuapp.com/posts/<%= post.id %>" data-hashtags="あるあるnet" data-lang="ja" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
</div>
<% end %>
<br>
<%= paginate posts %>

app/views/posts/_posts1.html.erb
<% posts.each do |post| %>
<div class="card mt-3">
  <div class="media-header bg-cream">
    <h5 class="ml-3 mt-1"><strong><%= link_to post.title+'あるある', post_path(post), class: 'text-dark' %></strong></h5>
  </div>  
  <div class="card-body">
   <p> <%= post.content %></p>
  </div>
  <div class="card-footer bg-white small">
    <%= render 'favorites/like_button', post: post %>
    　カテゴリー：<%= link_to post.category.type, '/posts/search?utf8=✓&search%5Bcategory_id%5D=' +  post.category.id.to_s + '&sort=id+desc&search%5Btext%5D=&commit=検索'%>
    　投稿者：<%= link_to post.user.name, user_path(post.user)%>
    <div class="mt-1" style="float: right; display: inline-block">
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="「<%= post.title %>あるある」　<%= post.content %>" data-url="https://9e822418fde248a88a819d46852f92f1.vfs.cloud9.us-east-1.amazonaws.com/posts/<%= post.id %>" data-hashtags="あるあるnet" data-lang="ja" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_posts2.html.erb
<% posts.each do |post| %>
<div class="card mt-3">
  <div class="media-header bg-cream">
    <h5 class="ml-3 mt-1"><strong><%= link_to post.title+'あるある', post_path(post), class: 'text-dark' %></strong></h5>
  </div>  
  <div class="card-body">
   <p> <%= post.content %></p>
  </div>
  <div class="card-footer bg-white small">
    <%= render 'favorites/like_button', post: post %>
    　カテゴリー：<%= link_to post.category.type, '/posts/search?utf8=✓&search%5Bcategory_id%5D=' +  post.category.id.to_s + '&sort=id+desc&search%5Btext%5D=&commit=検索'%>
    　投稿者：<%= link_to post.user.name, user_path(post.user)%>
    <div class="mt-1" style="float: right; display: inline-block">
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="「<%= post.title %>あるある」　<%= post.content %>" data-url="https://9e822418fde248a88a819d46852f92f1.vfs.cloud9.us-east-1.amazonaws.com/posts/<%= post.id %>" data-hashtags="あるあるnet" data-lang="ja" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_posts_jukkai.html.erb
<div class="container-fluid">
  <div class="row flex-wrap">
    <% posts.each do |post| %>
      <div class="col-sm-6">
        <div class="card mt-3">
          <div class="media-header bg-cream">
            <h5 class="ml-3 mt-1"><strong><%= link_to post.title+'あるある', post_path(post), class: 'text-dark' %></strong></h5>
          </div>  
          <div class="card-body">
           <p> <%= post.content %></p>
          </div>
          <div class="card-footer bg-white small">
            <div id="like_button-<%= post.id %>">
              <%= render 'favorites/like_button', post: post %>
            </div>
            　カテゴリー：<%= link_to post.category.type, '/posts/search?utf8=✓&search%5Bcategory_id%5D=' +  post.category.id.to_s + '&sort=new&search%5Btext%5D=&commit=検索'%>
            　投稿者：<%= link_to post.user.name, user_path(post.user)%>
            <div class="mt-1" style="float: right; display: inline-block">
              <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="「<%= post.title %>あるある」　<%= post.content %>" data-url="https://jepapt2-aruaru.herokuapp.com/posts/<%= post.id %>" data-hashtags="あるあるnet" data-lang="ja" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>









<br>

app/views/posts/_posts_top.html.erb
<% posts.each do |post| %>
<div class="card mt-3">
  <div class="media-header bg-cream">
    <h5 class="ml-3 mt-1"><strong><%= link_to post.title+'あるある', post_path(post), class: 'text-dark' %></strong></h5>
  </div>  
  <div class="card-body">
   <p> <%= post.content %></p>
  </div>
  <div class="card-footer bg-white small">
    <div id="like_button-<%= post.id %>">
      <%= render 'favorites/like_button', post: post %>
    </div>
    　カテゴリー：<%= link_to post.category.type, '/posts/search?utf8=✓&search%5Bcategory_id%5D=' +  post.category.id.to_s + '&sort=id+desc&search%5Btext%5D=&commit=検索'%>
    　投稿者：<%= link_to post.user.name, user_path(post.user)%>
    <div class="mt-1" style="float: right; display: inline-block">
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-text="「<%= post.title %>あるある」　<%= post.content %>" data-url="https://jepapt2-aruaru.herokuapp.com/posts/<%= post.id %>" data-hashtags="あるあるnet" data-lang="ja" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
</div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/new.html.erb
<div class="container"></div>
<h1>あるある投稿</h1>

<%= form_with(model: @post, local: true) do |f| %>

  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :title,'あるあるタイトル' %>
    <div class="form-inline">
      <%= f.text_field :title, class: 'form-control', :size=>"50" %>あるある
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :content,'本文' %>
    <%= f.text_area :content, class: 'form-control', :size => "60x5" %>
  </div>
  

  <div class="form-group">
    <%= f.label :category,'カテゴリー' %><br>
    <%= f.collection_select :category_id, Category.all, :id, :type, :include_blank => 'カテゴリを選択', class: "form-control" %>
  </div>
     

  <%= f.submit '投稿', class: 'btn btn-primary btn-block mt-5' %>
<% end %>

app/views/posts/search.html.erb
<h1>あるある検索</h1>

<%= form_with model: @post, :url => {:action => :search}, scope: :search, method: :get, local: true do |f| %>
<% category_id = params[:search][:category_id] if params[:search].present? %>
<% sort = params[:search][:sort] if params[:sort].present? %>
<% text = params[:search][:text] if params[:search].present? %>
<div class="form-inline mb-4">
  <div class="form-group mr-3">
    <%= f.label :category,'カテゴリー' %><br>
    <%= f.collection_select :category_id, Category.all, :id, :type, { include_blank: 'カテゴリを選択', disabled: true, selected: category_id }, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :sort,'並び替え' %><br>
    <%= select_tag :sort, options_for_select({'新着順': 'new', '古い順': 'old', 'お気に入りが多い順': 'popular', 'お気に入りが少ない順': 'unpopular'}),{class: "form-control" } %>
  </div>
</div>
  <div class="form-group">
    <%= f.label :text, 'テキスト検索' %>
    <%= f.text_field :text, value: text, class: "form-control" %>
    
  </div>
<%= f.submit '検索', class:'btn btn-secondary' %> 
  
<% end %>

<%= render 'posts/posts', posts: @posts %>

<% if @posts.empty? %>
  <div class="alert alert-secondary">該当する投稿がありませんでした</div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
    
  <h1>あるある詳細</h1>
    
  <%= render 'posts/post_show', post: @post %>
    
  <h4 class="mt-3"><%= link_to '←戻る', :back %></h4>

</div>