config/routes.rb
Rails.application.routes.draw do
  devise_for :users,only: [:registration, :sign_in, :sign_out, :session], :controllers => {
 :registrations => 'users/registrations',
 :sessions => 'users/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :only => [:show] do
    member do
      get :likes
    end
  end
      
root to: 'toppages#index'
  
  resources :posts, :only =>[:new,:create,:show] do
    get :search,  on: :collection
  end
  
resources :favorites, only: [:create, :destroy]

get 'gachas' => 'gachas#index'
get 'gachas/ikkai/' => 'gachas#ikkai'
get 'gachas/jukkai/' => 'gachas#jukkai'

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-cream">
    <a class="navbar-brand" href="/">あるある.net</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
  
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to 'あるある検索', '/posts/search?utf8=✓&search%5Bcategory_id%5D=&sort=id+desc&search%5Btext%5D=&commit=検索', class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ガチャ', gachas_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '投稿', new_post_path, class: 'nav-link' %></li>
        </ul>
        
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to 'ユーザ登録', new_user_registration_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
        
    
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>あるある.net</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
    
  </body>
</html>